FROM alpine:3.7
RUN dd if=/dev/urandom of=file1 bs=8 count=1
RUN dd if=/dev/urandom of=file2 bs=8 count=1
RUN dd if=/dev/urandom of=file3 bs=8 count=1
RUN dd if=/dev/urandom of=file4 bs=8 count=1

RUN dd if=/dev/urandom of=file1 bs=8 count=1
RUN dd if=/dev/urandom of=file2 bs=8 count=1
RUN dd if=/dev/urandom of=file3 bs=8 count=1
RUN dd if=/dev/urandom of=file4 bs=8 count=1
RUN dd if=/dev/urandom of=file4 bs=8 count=1

RUN dd if=/dev/urandom of=file1 bs=8 count=1
RUN dd if=/dev/urandom of=file2 bs=8 count=1
RUN dd if=/dev/urandom of=file3 bs=8 count=1
RUN dd if=/dev/urandom of=file4 bs=8 count=1
RUN dd if=/dev/urandom of=file4 bs=8 count=1

RUN dd if=/dev/urandom of=file1 bs=8 count=1
RUN dd if=/dev/urandom of=file2 bs=8 count=1
RUN dd if=/dev/urandom of=file3 bs=8 count=1
RUN dd if=/dev/urandom of=file4 bs=8 count=1
RUN dd if=/dev/urandom of=file4 bs=8 count=1
